---
- hosts: tf

  tasks:
    - name: add aliyun repository mirror
      become: true
      apt_repository:
        repo: deb http://mirrors.aliyun.com/ubuntu/ xenial main
        state: present

    - apt_repository:
        repo: deb-src http://mirrors.aliyun.com/ubuntu/ xenial main
        state: present
      become: true

    - name: Update all packages to the latest version
      apt:
        upgrade: dist
      become: true

    - name: install zsh
      apt:
        name: zsh
      become: true

    - user:
        name: "{{ ansible_ssh_user }}"
        shell: /bin/zsh
      become: true
    
    - name: check if oh_my_zsh installed, otherwise install it.
      stat: path=~/.oh-my-zsh
      register: oh_my_zsh
    
    - name: Download zsh installer
      get_url: 
        url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
        dest: /tmp/zsh-installer.sh
        mode: 0755
      when: oh_my_zsh.stat.exists == False

    - name: Execute the zsh-installer.sh
      command: sh -c /tmp/zsh-installer.sh
      when: oh_my_zsh.stat.exists == False

    - copy:
        src: tf.zsh-theme
        dest: ~/.oh-my-zsh/themes
        mode: 0644

    - lineinfile:
        path: ~/.zshrc
        regexp: '^ZSH_THEME=".*"$'
        line: 'ZSH_THEME="tf"'

    # install anaconda3 on remote host
    - stat: path=~/anaconda3
      register: anaconda3

    - script: res/Anaconda3-4.4.0-Linux-x86_64.sh -b
      when: anaconda3.stat.exists == false

    - name: set anaconda path in .zshrc file
      lineinfile: 
        state: present
        dest: ~/.zshrc
        regexp: '^export PATH={{ ansible_env.HOME }}/anaconda3/bin:\$PATH'
        line: 'export PATH={{ ansible_env.HOME }}/anaconda3/bin:$PATH'

