---
- hosts: tf

  tasks:
    # install anaconda3 on remote host
    - stat: path=~/anaconda3
      register: anaconda3

    - script: res/Anaconda3-4.4.0-Linux-x86_64.sh -b
      when: anaconda3.stat.exists == false

    - name: set anaconda path in .zshrc file
      lineinfile: 
        state: present
        dest: ~/.zshrc
        regexp: '^export PATH={{ ansible_env.HOME }}/anaconda3/bin:\$PATH'
        line: 'export PATH={{ ansible_env.HOME }}/anaconda3/bin:$PATH'
