---
- name: add ppa repository for nvidia driver install
  become: true
  apt_repository:
    repo: 'ppa:graphics-drivers/ppa'

# check and install nvidia driver from ppa
- name: Verify You Have a CUDA-Capable GPU
  shell: lspci | grep -i nvidia
  register: nvidia_card_check

- name: install nvidia drivers
  apt:
    name: nvidia-375
  become: true
  when: nvidia_card_check.rc == 0

# check nouveau drivers and Disabling it
- name: check Nouveau drivers are loaded
  shell: lsmod | grep nouveau
  register: nouveau_check
  ignore_errors: true

- name: copy nouveau to config file dir
  become: true
  copy:
    src: files/blacklist-nouveau.conf
    dest: /etc/modprobe.d/
    mode: 0644
  when: nouveau_check.rc == 0

- name: Regenerate the kernel initramfs
  become: true
  command: update-initramfs -u
  when: nouveau_check.rc == 0

# check runlevel and set to multi-user.target
- name: get default runlevel
  become: true
  command: systemctl get-default
  register: runlevel

- name: set default runlevel to multi-user.target
  become: true
  command: systemctl set-default multi-user.target
  when: runlevel.stdout != 'multi-user.target'

- include: reboot.yml
  when: runlevel.stdout != 'multi-user.target'

# check and install nvidia cuda toolkit and patch
- stat: path=/usr/local/cuda/version.txt
  register: cuda_toolkit

- name: run cuda tool kit install
  become: true
  script: files/cuda_8.0.61_375.26_linux.run --silent --toolkit --samples
  when: cuda_toolkit.stat.exists != true

- stat: path=/usr/local/cuda/version.txt
  register: cuda_toolkit

- name: get cuda toolkit version content
  command: cat /usr/local/cuda/version.txt
  register: cuda_toolkit_version
  when: cuda_toolkit.stat.exists is defined and cuda_toolkit.stat.exists

- name: run cuda tool kit patch install
  become: true
  script: files/cuda_8.0.61.2_linux.run --silent --accept-eula
  when: ( cuda_toolkit_version | skipped != true) and
        ( cuda_toolkit_version.stdout.find('CUDA Patch Version 8.0.61.2') == -1 )

# config path environment
- name: add cuda bin to path
  lineinfile:
    state: present
    dest: ~/.zshrc
    regexp: 'export PATH=/usr/local/cuda/bin:\$PATH'
    line: 'export PATH=/usr/local/cuda/bin:$PATH'

- name: add lib path to LD_LIBRARY_PATH
  lineinfile:
    state: present
    dest: ~/.zshrc
    regexp: 'export LD_LIBRARY_PATH=/usr/local/cuda/lib64:\$LD_LIBRARY_PATH'
    line: 'export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH'

- name: Extract cudnn driver into /usr/local
  become: true
  unarchive:
    src: files/cudnn-8.0-linux-x64-v{{ cudnn_version }}.tgz
    dest: /usr/local
    owner: root
    group: root
#    mode: 0644
