---
- include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
      - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
      - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"
      paths:
      - ../vars
      skip: true


- include: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
      - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
      - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"
      skip: true
