---
# proxy http://172.23.3.112:3128
#

- name: add aliyun repository mirror
  become: true
  apt_repository:
    repo: deb http://mirrors.aliyun.com/ubuntu/ xenial main
    state: present

- name: add aliyun repository mirror for src
  become: true
  apt_repository:
    repo: deb-src http://mirrors.aliyun.com/ubuntu/ xenial main
    state: present

- name: Update all packages to the latest version
  become: true
  apt:
    upgrade: dist
