---
- name: copy mkl package to remote
  copy:
    src: '{{ tar_file }}'
    dest: ~/tensorflow/tensorflow/third_party/mkl
  with_items:
    - large_files/mklml_lnx_2018.0.20170425.tgz
    - large_files/mklml_lnx_2018.0.20170720.tgz
  loop_control:
    loop_var: tar_file
