---
# install anaconda3 on remote host
- stat: path=~/anaconda3
  register: anaconda3

- script: large_files/Anaconda3-4.4.0-Linux-x86_64.sh -b
  when: anaconda3.stat.exists == false

- name: set anaconda path in .zshrc file
  lineinfile:
    state: present
    dest: ~/.zshrc
    regexp: '^export PATH={{ ansible_env.HOME }}/anaconda3/bin:\$PATH'
    line: 'export PATH={{ ansible_env.HOME }}/anaconda3/bin:$PATH'

# add douban pip source
- name: Ensure "fav=lemonade is in section "[drinks]" in specified file
  ini_file:
    path: ~/.pip/pip.conf
    section: global
    option: index-url
    value: https://pypi.douban.com/simple
    backup: yes

- ini_file:
    path: ~/.pip/pip.conf
    section: global
    option: trusted-host
    value: pypi.douban.com
    backup: yes
